plugins {
    id 'java'
    id 'org.springframework.boot' version '2.5.2' apply false
    id 'io.spring.dependency-management' version '1.0.11.RELEASE' apply false
}

allprojects {
    group = 'com.example'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }
}

tasks.register('copyReactApp', Copy) {
    group = 'build'
    description = 'Copy client resources into server'

    def src = "${project(':frontend').projectDir}/react-app/build"
    def dest = "${project(':backend').buildDir}/resources/main/static"

    from src
    into dest

    doLast {
        println("Copying frontend resources to include in spring boot jar")
        println("Copying ${src} to ${dest}")
    }
}
