rootProject.name = 'spring-boot-react-hateoas-template'

include 'backend'
project(':backend').projectDir = file('subprojects/backend')
project(':backend').buildFileName = 'backend.gradle'

include 'frontend'
project(':frontend').projectDir = file('subprojects/frontend')
project(':frontend').buildFileName = 'frontend.gradle'
